multus/multus.go

Bug fix to #2 issue, clear the master plugin network resources and minion plugin network resources, in the case of failure in anyone of the minion plugins.

fix to clear plugins after the failure

---

multus/multus.go

Refer CPU-Manager-For-Kubernetes fails to launch when using kubeconfig multus #14 for more info

Bug fix to provide default CNI networking.

---

multus/multus.go

Change-Id: Ie266603cff714998dd29bb62e3aa6de531b46c23

fix the cmdDel interface bug

---

README.md

- Added table of content
- Grouped Testing sub sections into a single section
- Moved contact subsection to appropriate location

Updating README to improve readability

---

multus/multus.go

Matching error text is error-prone, so use a typed error instead.

Use typed error when kubernetes network is missing

---

.travis.yml
README.md
multus/multus.go

Here's the wholesale set of changes that we had made in our fork, bringing them back in for either review, or we can bring them all in and work the changes separately.
The detail on each PR we made individually can be found [in the closed pull requests](https://github.com/redhat-nfvpe/multus-cni/pulls?q=is%3Apr+is%3Aclosed) in our fork.
Thanks Kural!
Attn: @rkamudhan @s1061123 @fepan

Network Plumbing Working Group CRD Spec Changes

---

k8sclient/k8sclient.go
multus/multus.go

bug fix for #56 & #57
Change-Id: If4f3db4dd01ca3330d5d36b8a2e4c5740def910a
Co-authored-by: Doug Smith <douglaskippsmith@gmail.com>
Co-authored-by: Tomofumi Hayashi <s1061123@gmail.com>
Co-authored-by: Dan Williams <dcbw@redhat.com>

code refractoring with separate k8s-client package

---

k8sclient/k8sclient.go

Print error in case of errror (for debuggability) and remove isJSON() becuase none called it.

Incorporate review comments in #58

---

k8sclient/k8sclient.go
types/types.go

see issue #61 and #62 for more info
Complete details in #59
Open source contributors
Co-authored-by: Doug Smith <dougbtv@users.noreply.github.com>
Co-authored-by: Tomofumi Hayashi <s1061123@users.noreply.github.com>
Co-authored-by: Dan Williams <dcbw@users.noreply.github.com>

added the k8s network plumbing wg network crd structure

---

k8sclient/k8sclient.go

check #63
Co-authored-by: Doug Smith <dougbtv@users.noreply.github.com>
Co-authored-by: Tomofumi Hayashi <s1061123@users.noreply.github.com>
Co-authored-by: Dan Williams <dcbw@users.noreply.github.com>

adding config and json CNI file support

---

examples/flannel-conf.yml
examples/macvlan-conf.yml

Here's updates to the examples that are compatible with the "3 modes of configuration operation" as recently modified. 
Fixes #70

[bugfix][docs] Updates examples to match spec criteria

---

k8sclient/k8sclient.go

Only modifies the existing process slightly, but, the gist: 
1. assumes that it's JSON
2. if it's not, validate the format against format as specified in de-facto standard
3. Send an error message if it's not, explain it couldn't be parsed

Comma-delimited format validation

---

examples/npwg-demo-1/01_crd.yml
examples/npwg-demo-1/02_clusterrole.yml
examples/npwg-demo-1/03_namespace1.yml
examples/npwg-demo-1/04_macvlan1.yml
examples/npwg-demo-1/05_vlan1.yml
examples/npwg-demo-1/06_flannel2.yml
examples/npwg-demo-1/11_pod_case1.yml
examples/npwg-demo-1/12_pod_case2.yml
examples/npwg-demo-1/13_pod_case3.yml
examples/npwg-demo-1/14_pod_case4.yml

@s1061123 I went ahead and added your demo files into a `./examples/demo` directory -- but, I also went ahead and updated them so that they match the spec section that looks like:
```
metadata:
name: flannel-conf
spec: 
config: '{
"cniVersion": "0.3.0",
```
E.g. now the `plugin:` top level element is gone, and the `"type": ` element is under `spec.config`. 
Tomo, feel free to commit to this branch to show the changes, or, we can later delete this branch if you want to do it another way.
*note* Don't merge this yet, just for discussion of the demo examples for now, can merge later if we keep this branch, or close out the PR if we don't need it.

Demo examples including updates

---

multus/multus_test.go

multus: unit test multi-network interface names

---

README.md
types/conf.go
types/types.go

To be merged into 
I realize that only the API is available at the moment, and that the additional logging needs to be added in other parts of the code, however, I figured we could get a jump on having some docs available.
Tomo, please feel free to correct if there's somethings that I missed from the code, or otherwise had incorrect.
For example, I wrote that the `STDERR` logging is always performed, even though I see there's places where you could in theory turn it off -- but, I see that it isn't exposed to the user via the configuration file, so I wrote that it happens always.

[docs] Adds documentation for logging enhancements

---

README.md
examples/README.md
examples/crd.yml
examples/flannel-conf.yml
examples/macvlan-conf.yml
k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
testing/testing.go
types/conf.go
types/types.go

To align with latest spec change clarifying the name of the CRD object.
@s1061123 @dougbtv @rkamudhan

k8sclient: Network -> NetworkAttachmentDefinition

---

README.md

Deprecates the references to TPRs, some formatting fixes. With an eye towards what's available in 3.0

README updates for v3.0

---

k8sclient/k8sclient.go
multus/multus.go

fixing multus runtime error for network status without pod network annotation

---

images/70-multus.conf

Enable hairpinMode in the delegate config

---

multus/multus.go

Refer #115 for more information

Handling the multiple cmd del call from kubelet

---

.travis.yml
README.md

Adds `.travis.yml` updates to run coveralls, using [goveralls](https://github.com/mattn/goveralls).
Also adds CI badges to README.md
meta topic: Should we start a `develop` branch to merge these commit into for release together later?

Coveralls Code Coverage

---

examples/npwg-demo-1/01_crd.yml
examples/npwg-demo-1/02_clusterrole.yml

Almost files in npwg-demo-1 are fixed but I found several files
still use old definitons. This changes fix the stuff.

[docs]Updates npwg-demo-1 files to track latest changes

---

.travis.yml

This change fixes #143, to make some specific TravisCI args parameter.

TravisCI yaml parameterized

---

Dockerfile

Signed-off-by: Shahar Klein <shaharklein@gmail.com>

Seems like the ENTRYPOINT value must be quoted

---

images/flannel-daemonset.yml
images/multus-daemonset.yml

Addresses having stuck in pod queue in Kubernetes 1.12.x 
Fixes #170

Update flannel daemonset 

---

multus/multus.go

Synopsis: If there's a failure of deleting one plugin, we break out of the loop where we delete and fail to delete any subsequent plugins. This can leave previously used plugins in a faulty / dirty state if they're not properly
Example: If the default network plugin uses resources (let's say, it allocates IP addresses, and doesn't deallocate them until delete is called, as is the case with OpenShift-SDN), and an additional plugin is added for a secondary interface -- and that secondary interface cannot be created (wrong configuration, binary is missing, etc), we go to call delete on it, and the delete is also fails. Since we delete in LIFO order, the secondary interface deletion fails, and the default network deletion never happens. So if the default network required a delete in order to …

[bugfix] Delete all delegates instead of breaking out during deletion loop

---

Dockerfile
Dockerfile.rhel

Creates a new Dockerfile specific to OpenShift builds

[dockerfile] Adds Dockerfile.rhel for OpenShift build

---

doc/configuration.md

Add document for PR #174 
Fixes #200

Add doc for specifying pod default cluster network

---

images/entrypoint.sh

Seems like a typo in the original.

 add MULTUS_CONF_FILE to the arr for checking

---

images/70-multus.conf

Solves https://github.com/intel/multus-cni/issues/208

Add port forwarding to config provided by the docker image

---

doc/how-to-use.md

Change-Id: I3d7db11bf6216c2e1ddcab9d61c0c8e4fb8c0010
Signed-off-by: Moshe Levi <moshele@mellanox.com>

Fix multus dir creation in how-to-use.md

---

multus/multus.go
multus/multus_test.go
types/conf.go

@s1061123 @dougbtv @rkamudhan @danwinship

multus: simplify teardown on add error and clarify error message

---

doc/quickstart.md

[docs] Adds note about master device name

---

doc/configuration.md
k8sclient/k8sclient.go
multus/multus.go
types/conf.go
types/conf_test.go
types/types.go

This change provides new configuration parameters, multusNamespace
and systemNamespaces for flexible namespace management.
The change addresses issue #252 and issue #253.

 Add multusNamespace/systemNamespaces config

---

k8sclient/k8sclient.go
k8sclient/k8sclient_test.go

Change ClusterNetwork/DefaultNetwork namespace to MultusNamespace

---

multus/multus.go
multus/multus_test.go

Signed-off-by: Huanle Han <hanhuanle@caicloud.io>

fix crash caused by empty delegates when use clusterNetwork

---

images/entrypoint.sh

Waits for a file to be present in the CNI configuration directory when using the `--multus-conf-file=auto `

Adds wait loop to entrypoint when --multus-conf-file=auto 

---

types/conf.go

This patch fixes the issue described in #289 where deviceID for
delegate plugin was not adding properly if the plugin conf inside
NetConfList.
Change-Id: I1d221f6b0e60a5b888b8e823611dfe12635e6897
Signed-off-by: Abdul Halim <abdul.halim@intel.com>

fix missing deviceID in NetConfList

---

multus/multus.go

Skips the clearing of the network status annotation in the case where the pod sandbox is missing.
This would cause spurious error logs that weren't valuable when this was otherwise a known condition.
Previously, if you created a pod, and then force deleted it, such as:
```
$ kubectl delete pod samplepod  --grace-period=0 --force 
```
You'd get errors such as:
```
2019-05-03T12:46:06Z [debug] cmdDel: WARNING netns may not exist, netns: %!s(<nil>), err: failed to Statfs "/proc/11646/ns/net": no such file or directory
[...snip...]
2019-05-03T12:46:06Z [error] SetNetworkStatus: failed to query the pod samplepod in out of cluster comm: pods "samplepod" not found
2019-05-03T12:46:06Z [error] Multus: Err unset the networks status: SetNetworkStatus: failed to query the pod samplepod in out of …
```

[bugfix] Skipped clearing the status annotation if the pod sandbox is missing

---

doc/configuration.md

Add verbose loggingLevel option to configuration documentation

---

doc/quickstart.md
examples/sample-pod.yml

changes sleep in docs to example that uses a trap INT

[minor][docs] changes sleep in docs to example that uses a trap INT

---

images/entrypoint.sh

Found that the missing help text, during the #335 conversation

Add help text for '--cni-version'

---

checkpoint/checkpoint.go
checkpoint/checkpoint_test.go
logging/logging_test.go
types/conf_test.go

Increased code coverage up to 96.4% in checkpoint_test.go

Unit Tests - checkpoint_test.go code coverage improvement

---

.travis.yml
Dockerfile.ppc64le
images/multus-daemonset-crio.yml
images/multus-daemonset.yml

Multi architecture image and CI job

---

doc/how-to-use.md
images/entrypoint.sh
images/multus-daemonset-crio.yml

Tomo, here's the changes for the watch loop & the CRIO restart. I added a parameter to enable the CRIO restart. Let me know if you see anything that needs changes. Feel free to push commits to my branch, too.
I'll also follow up with a PR for the cluster-network-operator to hopefully enable this.

Entrypoint changes for watchloop & CRIO restart

---

images/entrypoint.sh

Two changes:
* Makes CRIO restart a one-shot, it can only happen once per script run
* Restore capability to rename source CNI config to .old when not using the watch loop
@s1061123 -- can you check and see if the condition for the rename of the file looks like what we should be doing? Thank you!

[entrypoint] Adds one-shot CRIO restart, plus renames source CNI conf to .old

---

doc/configuration.md
doc/how-to-use.md
images/entrypoint.sh

Adds --additional-bin-dir option to entrypoint to add binDir configuration option
As well as doc updates.

[entrypoint] Adds --additional-bin-dir option to entrypoint

---

doc/development.md

Fixes #382 
Minor improvements to sentence structure in development documentation.
Signed-off-by: tdorsey@gmail.com

Fix minor grammatical errors

---

checkpoint/checkpoint.go
k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
kubeletclient/kubeletclient.go
multus/multus.go
multus/multus_test.go
types/conf.go

This diff changes error message with fixed format for easy-to-read for users.
- Add function name at the top, without bracket
- don't start with upper-letter
- remove 'see README.md' text

Improve error message

---

doc/how-to-use.md
k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
multus/multus.go
multus/multus_test.go
netutils/netutils.go
types/conf.go
types/types.go

Additionally, changes config JSON from to use the `default-route` terminology, and adds to docs

[WIP] Support gateway in NetworkSelectionElement

---

multus/multus_test.go

This change addresses the CI failure:
https://travis-ci.org/intel/multus-cni/jobs/611917037

Fix unit test to track on updated error message

---

multus/multus.go
multus/multus_test.go

Add CNI Check support
Add tests for CNI version 0.4.0

Add CNI Check support

---

multus/multus.go

Would wait every single time without the file being present.

[bugfix] Fixes unnecessary wait when readinessindicatorfile is not present

---

Dockerfile.arm64

Add Dockerfile.arm64 for building Multus image on arm64.
Thanks

Add Dockerfile for building image on arm64

---

multus/multus.go

Adds readinessindicatorfile check on CNI DEL

---

k8sclient/k8sclient.go
k8sclient/k8sclient_test.go

Corrected the error for missing network-attachment-definition

Error log for network-attachment-definition

---

doc/development.md

For discussion at maintainers meeting.

Adds development docs note regarding issue policy

---

k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
multus/multus.go

Add deviceid in clusterNetwork

---

multus/multus.go

This change adds retry to wait a bit if kubernetes client
returns service unavailable.
This fixes #492

Change the error handling for kubernetes client

---

README.md

This updates the links to point to "doc/" instead of "docs/"

The readme links need to be updated after directory change.

---

README.md

Signed-off-by: Kennelly, Martin <martin.kennelly@intel.com>.

Update Slack URL in README following renaming

---

pkg/k8sclient/k8sclient.go

Return error on annotation parsing error

---

.github/workflows/kind-e2e.yml
e2e/simple-pod.yml
e2e/test-simple-pod.sh
pkg/k8sclient/k8sclient.go

[WIP] Change nil instead of error in case of no network annotation

---

docs/development.md

For a bi-annual release if no version has been tagged recently.
Fixes #622

[docs] Adds release policy

---

pkg/multus/multus_test.go
pkg/types/conf.go
pkg/types/conf_test.go

Add cluster network name in pod network annotation

---

images/entrypoint.sh

This is essentially to be very very careful.
From having seen errors in OpenShift CI that looks like:
```
Multus: error getting k8s client: GetK8sClient: failed to get context for the kubeconfig /etc/kubernetes/cni/net.d/multus.d/multus.kubeconfig: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

The kubeconfig creation should be an atomic operation

---

pkg/k8sclient/k8sclient.go
pkg/kubeletclient/kubeletclient.go
pkg/kubeletclient/kubeletclient_test.go

Remove global variables from kubletclient

---

docs/configuration.md

examples: missing cni version on version without delegates

---

pkg/multus/multus.go

When checking the pod UID, on CNI DEL, we should not error out.
The pod UID can mismatch in the case of a stateful set (for example) and the pod namespace and name remain the same, but the pod UID changes. Erroring on DEL can cause the pod to not be properly cleaned up.
In this case, we can just return without the current results from the API about the pod, and simply operate on the cache in order to make the delete.

Pod UID mismatches should only warn on CNI DEL

---

pkg/multus/multus.go
pkg/netutils/netutils.go
pkg/netutils/netutils_test.go

Format the golang code located in `pkg/...` and `cmd/...`

run gofmt on the code

---

cmd/controller/main.go

now the usage of flag "overrideNetworkName" is incomplete. so this pr will fix it.

fix the usage of flag "overrideNetworkName"

---

pkg/multus/multus_cni020_test.go
pkg/multus/multus_cni040_test.go

Some of tests are duplicated hence deduped. In addition, sort
these unit tests based on cniVersion.

Refine unit test in pkg/multus

---

cmd/controller/main.go
docs/configuration.md
pkg/config/generator.go
pkg/config/generator_test.go
pkg/logging/logging.go
pkg/logging/logging_test.go
pkg/testing/testing.go
pkg/types/conf.go
pkg/types/conf_test.go
pkg/types/types.go

Fixes: https://github.com/k8snetworkplumbingwg/multus-cni/issues/814
adding some flags for customize the log settings, such as`MaxSize`, `MaxBackups`, `MaxAge` etc.

add some flags for customize the log settings

---

cmd/multus-daemon/main.go
deployments/multus-daemonset-thick.yml
docs/how-to-use.md
docs/thick-plugin.md
e2e/templates/multus-daemonset-thick.yml.j2
images/entrypoint.sh
pkg/k8sclient/k8sclient.go
pkg/netutils/netutils_test.go
pkg/server/exec_chroot.go
pkg/server/server.go
pkg/server/shim.go
pkg/types/conf.go
pkg/types/types.go

This change introduces 'chroot' option in multus-daemon to execute
delegate CNI with host filesystem context.
fix #829

Add chroot option in multus-daemon

---

pkg/k8sclient/k8sclient.go

remove redundant type conversion

delete type conversion

---

.github/workflows/kind-e2e.yml
e2e/setup_cluster.sh
e2e/simple-static-pod.yml
e2e/static-pod-nad.yml
e2e/test-static-pod.sh

Created a bash e2e test that creates a static pod, checks for net1 interface, and cleans up afterward.

Static pod e2e

---

images/Dockerfile
images/Dockerfile.arm32
images/Dockerfile.arm64
images/Dockerfile.ppc64le
images/Dockerfile.s390x
images/Dockerfile.thick

Update golang version to 1.18.x

---

images/entrypoint.sh

fixes https://github.com/k8snetworkplumbingwg/multus-cni/issues/880
Signed-off-by: <chrisplo@cisco.com>

Detect python3

---

.github/workflows/test.yml
go.mod
go.sum
vendor/github.com/containernetworking/cni/libcni/conf.go
vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
vendor/github.com/containernetworking/cni/pkg/skel/skel.go
vendor/github.com/containernetworking/cni/pkg/version/plugin.go
vendor/github.com/onsi/gomega/CHANGELOG.md
vendor/github.com/onsi/gomega/gomega_dsl.go
vendor/github.com/onsi/gomega/internal/assertion.go
vendor/github.com/onsi/gomega/internal/async_assertion.go
vendor/github.com/onsi/gomega/internal/gomega.go
vendor/github.com/onsi/gomega/matchers.go
vendor/github.com/onsi/gomega/matchers/have_field.go
vendor/github.com/onsi/gomega/matchers/have_http_body_matcher.go
vendor/github.com/onsi/gomega/matchers/have_http_header_with_value_matcher.go
vendor/github.com/onsi/gomega/matchers/have_http_status_matcher.go
vendor/github.com/onsi/gomega/matchers/with_transform.go
vendor/github.com/onsi/gomega/types/types.go
vendor/modules.txt

This change introduces https://github.com/containernetworking/cni/pull/904
to fix the issue.

Bump libcni to fetch the bugfix

---

deployments/multus-daemonset-crio.yml
deployments/multus-daemonset-gke-1.16.yml
deployments/multus-daemonset-thick.yml
deployments/multus-daemonset.yml

This change adds note section in deployment yaml to explicitly mention the scope of this yaml.

Update deployment yaml

---

images/Dockerfile
images/Dockerfile.arm32
images/Dockerfile.arm64
images/Dockerfile.ppc64le
images/Dockerfile.s390x
images/Dockerfile.thick
images/entrypoint.sh

This change introduce fedora container for multus image. Fix #898

[WIP]Change container image to python:slim from centos

---

README.md

Signed-off-by: Jan Klare <jan.klare@bisdn.de>

rephrase readme section describing thin vs thick plugin

---

images/Dockerfile
images/Dockerfile.arm32
images/Dockerfile.arm64
images/Dockerfile.ppc64le
images/Dockerfile.s390x
images/Dockerfile.thick
images/entrypoint.sh

This change introduce fedora container for multus image.

[backport v3] Change container image to fedora from centos

---

pkg/server/api/api.go
pkg/server/server.go

Fix deleate API to load conflist

---

go.mod
vendor/modules.txt

Fix kubelet version in go.mod

---

docs/how-to-use.md

Add EOF to the Cat command, otherwise the operation will fail

Add "EOF" to the Cat command, otherwise the operation will fail

---

cmd/multus-daemon/main.go
go.sum
pkg/server/config/manager.go
pkg/server/config/manager_test.go

This fix the issue #931 to refining server startup code including file copy and channel processing, with simplification.

Fix multus-daemon in case of user given config

---

e2e/test-simple-macvlan1.sh

modify test-simple-macvlan1.sh

Modify the judgment of test results

---

cmd/multus-daemon/main.go

Let the info note aligned.
/kind cleanup

Capitalization for option descriptions

---

e2e/test-default-route1.sh

add check test result for interface net1
@s1061123

add check test result for interface net1

---

cmd/multus-daemon/main.go
pkg/server/config/generator.go
pkg/server/config/generator_test.go
pkg/server/config/manager.go

To update mutations for configuration for socketfile and cniconf dir.

Updates config options and tests for socketfile and cniconfdir

---

pkg/checkpoint/checkpoint.go
pkg/kubeletclient/kubeletclient.go

update the notes for the right method.

clean wrong notes.

---

images/entrypoint.sh

align case line .

---

.github/workflows/image-build.yml

Add workaround patch for okd-builder.Dockerfile build failure

---

cmd/thin_entrypoint/main.go

This change removes unnecessary comment.

Cleanup code comment

---

deployments/multus-daemonset-thick.yml

Add 'cniConfigDir' to specify config dir

---

deployments/multus-daemonset-thick.yml

Fix incorrect mount volume name in the thick plugin manifest

---

cmd/cert-approver/main.go
cmd/multus-daemon/main.go
cmd/thin_entrypoint/main_test.go
pkg/server/api/api.go
pkg/server/api/shim.go
pkg/server/config/config_suite_test.go
pkg/server/config/generator_test.go
pkg/server/config/manager_test.go

Add timeout

---

.github/workflows/image-build.yml
.github/workflows/image-push-master.yml
.github/workflows/image-push-release.yml

Fixes: https://github.com/k8snetworkplumbingwg/multus-cni/issues/1281

arm64: build image for arm v8

---

.github/workflows/kind-e2e.yml

Related to issue #1333 
We'll temporarily disable this so we can properly test other PRs in the meanwhile

Disabled DRA test temporarily

---

pkg/multus/multus.go

This change adds toleration for such errors like:
```
failed to [query/update] the pod pod-name-here in out of cluster comm: pod "pod-name-here" not found
```
During CNI ADD. While this change is a trade off in terms of debugability for RBAC, it's potentially noisy in scaled clusters when it is working properly.

Tolerate issues writing network status annotation on CNI ADD.

---

pkg/multus/multus.go

For a previous fix of returning an empty CNI result when pods are not found, the CNI result wasn't properly structured. This fixes the structuring.

Properly structure empty CNI result

---

images/Dockerfile
images/Dockerfile.debug

chore: update Dockerfile base image
