k8snetworkplumbingwg/multus-cni

multus/multus.go

The API endpoint wasn't exactly correct after the initial changes to use the new namespace. I was running a test of the new `dev/network-plumbing-working-group-crd-change`, and found that the API endpoint was in need of a modification.
Was:
```
/apis/kubernetes-network.cni.cncf.io/v1/namespaces/default/networks/%s
```
Which was returning a 404.
Changed endpoint to:
```
/apis/cni.cncf.io/v1/namespaces/default/kubernetes-network/%s
```
(Where `%s` is the particular network name, e.g. a configuration a user has loaded)
I also updated the error output to put the error returned from the API, comments/criticism of that (or any other) change highly appreciated. I mostly put it there as I've run into an error in the same spot a few times, previous due to RBACs being wrong on my end, and this time …

Fix API call for new CRD namespace

---

k8sclient/k8sclient.go
multus/multus.go

This fix changes type type for NoK8sNetworkError due to error handling, in #45.
Currently NoK8sNetworkError is not pointer type, just a string, hence we never
get *NoK8sNetworkError. This fix changes it based @One-ders patch.

Fix error type for NoK8sNetworkError

---

README.md
examples/README.md
examples/clusterrole.yml
examples/cni-configuration.conf
examples/crd.yml
examples/flannel-conf.yml
examples/macvlan-conf.yml
examples/multus-with-flannel.yml
examples/sample-pod.yml

Notably -- this should be considered as just "a working example" I believe that we should refine this later with what we agree should be the environment for the demo. However, this is (generally speaking) the process I've been using to make sure everything is in working order.
Includes:
* An `./examples` directory with a README showing process to use the examples.
* An update to the primary README with a link to the examples directory.
* Reference config file, reference Multus + Flannel deployment daemonset (with RBACs).
* Example clusterrole to give access to the `system:node:*` users.
* Example CRD and CRD objects.
* Example pod spec with an annotation.

Examples for CRD w/ Defacto Standard

---

README.md
examples/README.md
examples/cni-configuration.conf
examples/multus-with-flannel.yml
multus/multus.go
types/types.go

This fix removes 'masterplugin' and 'always_use_default' from multus config file. default network, defined in
/etc/cni/net.d/*conf should be master and this network should be used as default from network plumbing working group draft.

Refine multus config file (masterplugin and always_use_default)

---

examples/npwg-demo-1/11_pod_case1.yml
examples/npwg-demo-1/12_pod_case2.yml
examples/npwg-demo-1/13_pod_case3.yml
examples/sample-pod.yml

This is really a minor documentation fix, but, in tandem with the recent changes to the CRD name change, and the change from `s/kubernetes.v1/k8s.v1/` in the namespace, I went ahead and made the changes to the sample files as well.

[minor] Updates kubernetes.v1 to k8s.v1 in the sample files

---

.travis.yml
README.md
images/70-multus.conf
images/Dockerfile
images/README.md
images/entrypoint.sh
images/flannel-daemonset.yml
images/multus-daemonset.yml

Updates for a Docker image + Daemonset.
General idea is this is used to distribute Multus. The Docker image has instructions for compiling Multus. Using the Daemonset, host volumes from each node/master are exposed to the container as mounts, Multus binary & configuration are copied there. 
Also generates a kubeconfig using service account token auth, and includes RBAC for that service account.
Changes:
* Adds Docker image
* Has Travis changes to build & push Docker image
* Includes quickstart guide in the README.md
* Includes daemonset(s)

Docker image, Daemonset, Quickstart Guide

---

k8sclient/k8sclient.go
logging/logging.go
logging/logging_test.go
multus/multus.go
types/conf.go

This changes adds initial logging messages:debug and error. 
Error messages:
fmt.Errorf() is wrapped by logging.Errorf() hence all error message is also put to log file. 
Debug messages:
Added logging.Debugf() at the head of almost func, so we could track the code by logging message.

Add logging message for debug/error

---

glide.yaml

This change fixes glide.yaml: track on cni's subpackage change and some error about bytes package. With this change, verified that 'glide up' works without any error.

Fix glide.yaml

---

README.md

We'll remove from now, thanks for the suggestion guys -- we can put it back when we improve coverage.

[docs] Remove coveralls badge from README

---

README.md
examples/multus-ptp-portmap.conf
multus/multus.go
multus/multus_test.go
types/conf.go
types/conf_test.go
types/types.go

This patch fixes #29 for the portmap feature. Adding capabilities to the multus plugin attribute list is needed for the libcni to add portmappings infos in the runtimeConfig section.

Add portmap capability support

---

checkpoint/checkpoint.go
checkpoint/checkpoint_test.go
examples/README.md
examples/net-resource-sample-pod.yaml
examples/sriov-net.yaml
k8sclient/k8sclient.go
types/conf.go
types/types.go

Enabling kubelete checkpoint file  parsing to get Pod device info
so that these device information can be passed into CNI plugins that
need specific device information to work on.
Change-Id: I6630f56adc0a8307f575fc09ce9090c1ffca0337

parse kubelet checkpoint file for pod devices

---

README.md

The Logging Options section of README describes how to specify a file
to log to.  There is a typo, LogFile should be logFile to match the
json.
Fixes #177
Signed-off-by: Michael Cambria <mcambria@redhat.com>

Fix logFile to match configuration json

---

.travis.yml
Dockerfile
README.md
checkpoint/checkpoint.go
checkpoint/checkpoint_test.go
examples/README.md
examples/net-resource-sample-pod.yaml
examples/sriov-net.yaml
images/README.md
images/entrypoint.sh
k8sclient/k8sclient.go
multus/multus.go
multus/multus_test.go
types/conf.go
types/conf_test.go
types/types.go

Updates to stable branch based on discussion.
Chiefly omits:
adbea5a fixing readme file version details
a4f5fd4 Add portmap capability support
Also note:
Required modifications to 21cdfe5 resulting in a conflict due to changes in `types.go` likely due to git's difficulty creating a diff in the types due to both changes close to one another, and sweeping changes due to formatting.

Updates to release-v3 stable branch

---

multus/multus.go

conflistAdd() finds binaries differently than conflistDel().
Make the two call find binaries the same way.
Fixes #179
Signed-off-by: Michael Cambria <mcambria@redhat.com>

Make conflistDel() behave like conflistAdd()

---

README.md
k8sclient/k8sclient.go
multus/multus.go
multus/multus_test.go
types/conf.go
types/types.go

This change supports `mac` to specify MAC address for interface. This feature interworks with the latest 'tuning' CNI plugin of CNCF repo (https://github.com/containernetworking/plugins) and change MAC address.

Support 'mac' to specify MAC address for interface

---

README.md
examples/npwg-demo-1/12_pod_case2.yml
multus/multus_test.go
types/types.go

Change the Network Attachment Selection Annotation long-form
interface name request JSON key from 'interfaceRequest' to
'interface' to conform with the V1 NPWG spec.
@s1061123 @dougbtv @rkamudhan

CRD: interfaceRequest -> interface (v1 spec conformance)

---

multus/multus.go

When setting MAC in CNI_ARGS it overrides the existing CNI_ARGS.
This PR changes the code to append the MAC to the existing CNI_ARGS.

Setting the MAC in CNI_ARGS shouldn't override the existing CNI_ARGS

---

multus/multus.go
multus/multus_test.go
types/conf.go
types/types.go

Currently the IP is read from the pod network annotation into the NetworkSelectionElement.IPRequest but is not passed further to DelegateNetConf.IPRequest and then to the CNI_ARGS.
This PR fixes it.
The PR also includes some test fixes for both MacRequest and IPRequest (even the MacRequest was already passed correctly it seems the multus_test didn't actually tested it).
Note: the PR assumes the format of the IP on the network annotation is ips: "ip_address" as it was previously assumed by the code read the IP from the pod network annotation into NetworkSelectionElement.IPRequest.
Although it doesn't comply with the de-facto standard specifies the format is ips: ["ip1", "ip2", ...]

Support IPRequest to specify IP address for interface

---

k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
multus/multus_test.go
testing/testing.go

Allow pod to specify cluster default network in annotations, When more than one cluster network is available.
Create a new field 'k8s.v1.cni.cncf.io/default-network' in pod annotations, which is used to overwrite the cluster default network defined in Multus config file.
Fix #158

Specify Pod default network in Annotations

---

k8sclient/k8sclient.go

Before this change, error returned by `libcni.ConfFiles` was
silently ignored.
Signed-off-by: Michal Rostecki <mrostecki@suse.de>

k8sclient: Add missing error check

---

doc/configuration.md
k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
types/types.go

Further description shamelessly taken from the docs!
General idea is that we add a `namespaceIsolation` configuration parameter and then we compare the pod's namespace with the namespace of the custom resource that we're going to look for -- if they don't match when `namespaceIsolation` is enabled, then we error out. Tests and documentation included.
---
The functionality provided by the `namespaceIsolation` configuration option enables a mode where Multus only allows pods to access custom resources within the namespace where that pod resides. For example, if a pod is created in the namespace called `development`, Multus will not allow networks to be attached when defined by custom resources created in a different namespace, say in the `default` network.
Consider the situation where you …

[feature] Namespace isolation for custom resources

---

images/flannel-daemonset.yml

The cni configmap implies that flannel does something with port forwarding. I commented it out to make clear that it has no effect.

Remove unused config in flannel-daemonset.yaml

---

.goreleaser.yml
.travis.yml
build
multus/multus.go
multus/multus_test.go

This changes introduce new release/CI pipeline as following:
- Changes cross-compile/deploy tool from goxc to goreleaser
- Fix .travis.yml to run CI in forked repo (see below example)
- Add '-v'/'-version' command to show multus-cni version
example: https://travis-ci.org/s1061123/multus-cni/builds/464208823

Renew release/CI pipeline.

---

images/entrypoint.sh

Allows you to pass options such as:
```
./entrypoint.sh --multus-conf-file=auto --namespace-isolation=true
```
to wind up with:
```
"namespaceIsolation": true,
```
In your CNI configuration for Multus.

[entrypoint] Adds option for namespaceIsolation in entrypoint

---

images/entrypoint.sh

Theory behind this one is that if we're upgrading Multus using a daemonset, and we copy the file in... During the period where the binary is copied, there's a chance we'll execute a binary that isn't complete.
If instead, we copy the binary to a temporary location and then `mv -f ...` the file to the final location (i.e. to `/opt/cni/bin/multus`) we'll reduce the amount of time where we don't have a valid binary to execute.

Updates entrypoint for atomic move of binary

---

doc/how-to-use.md

Fixed the internal link to the 'create-network-attachment-definition' section.
The previous link pointed to the `dev/update-readme` branch of @s1061123

Fixed the internal link to the 'create-network-attachment-definition' section.

---

types/conf.go

This fixes the issue described in #211 where LoadNetworkStatus is
throwing in errors if a delegate plugin returns empty Result that
contains no IPAM information.
This change will allow ignoring the errors propagated from parsing
an empty Result and continue with next one.
Change-Id: Ife4b6103de044256233d581fa74759423ed94ff5

create empty NetworkStatus for empty Result struct

---

k8sclient/k8sclient.go

Alters the configuration we use to tell Multus to use a gRPC connection to the Kube API as opposed to JSON (which is default)

Changes configuration for kube api to use protobuf

---

multus/multus.go

More detail in the referenced issue. Generally the gist is that while a pod is in a failed state, the netns that Multus receives doesn't exist and the `cmdDel` function returns prematurely. With the premature return, we don't call the delegates during the delete -- in the case that the delegated CNI plugin needs to perform cleanup functions, this can leave it in a dirty state.
This fix lets the cmdDel continue.
Fixes #267

Allows cmdDel to finish if netns doesn't exist

---

images/entrypoint.sh

During deployment, the daemonSet will alway generate the multus config file no matter if file '00-multus.conf' exists or not.
Fixes: #265

Generate Multus config file regardless

---

logging/logging.go
logging/logging_test.go
multus/multus.go

This change address #274 to add 'verbose option which outputs minimum information (for usual runs with a bit information than 'error').
Following is the example output:
```
2019-02-28T07:08:21Z [verbose] Add: default:pod-case-01:default-cni-network:eth0 {"cniVersion":"0.3.1","interfaces":[{"name":"cni0","mac":"0a:58:0a:f4:02:01"},{"name":"veth49cb42db","mac":"32:2c:67:42:ea:10"},{"name":"eth0","mac":"0a:58:0a:f4:02:03","sandbox":"/proc/23187/ns/net"}],"ips":[{"version":"4","interface":2,"address":"10.244.2.3/24","gateway":"10.244.2.1"}],"routes":[{"dst":"10.244.0.0/16"},{"dst":"0.0.0.0/0","gw":"10.244.2.1"}],"dns":{}}
2019-02-28T07:08:22Z [verbose] Add: default:pod-case-01:vlan-conf-1-1:net1 {"cniVersion":"0.3.0","interfaces":[{"name":"net1","mac":"52:54:00:12:5b:4e","sandbox":"/proc/23187 …
```

Add 'verbose' option to logging minimum information

---

images/entrypoint.sh

Adds options to specify log level & log file in entrypoint when using config file autogeneration.
Additionally, remove exit on unknown argument for future compatibility in the, ahem, future.

Add options to specify logfile & loglevel in entrypoint

---

k8sclient/k8sclient.go
multus/multus.go

Properly set k8sclient before quiring pod information in SetNetworkStatus method.
k8sclient has a nul value when multus calls SetNetworkStatus method which leads to the runtime panic.
Fixes https://github.com/intel/multus-cni/issues/281

Properly initialize kubeClient in SetNetworkStatus method

---

.travis.yml
images/multus-crio-daemonset.yml
images/multus-daemonset.yml

This PR updates our image tagging scheme, now the `:latest` tagged image will be equivalent to `:snapshot` (we keep snapshot for historical reasons, but, both `:latest` and `:snapshot` will now be the builds from the tip of master)
In order to retain stability for users -- this also updates the daemonsets to point at a tagged release image -- in this case, it anticipates the `:v3.2` tag.
In preparation for this, and before the release v3.2 is tagged -- I have tagged a v3.2 release image so we can merge this now before we officially tag. So that users aren't stuck with a daemonset that can't pull an image. That image tag will be overwritten when we make the tag. (image tags viewable here: https://hub.docker.com/r/nfvpe/multus/tags)
Fixes #260

Updates image tagging / adds version tagged images to Daemonsets

---

examples/multus-with-flannel.yml
examples/npwg-demo-1/06_flannel2.yml
images/flannel-daemonset.yml
images/multus-crio-daemonset.yml
images/multus-daemonset.yml

With RollingUpdate update strategy, after you update a DaemonSet template, old DaemonSet pods will be killed, and new DaemonSet pods will be created automatically, in a controlled fashion.
I added this configuration in order to deal with updates automatically at the moment of updating multus/etc docker image version in running DaemonSets

Enable Rolling Update on defined DaemonSets

---

doc/quickstart.md

The flannel yaml in the example is using 10.244.0.0/16. If user bootstraps
a k8s cluster with different pod cidr, pod traffic will not go thru the flannel
vxlan tunnel.

Add pod cidr indication in quickstart doc

---

multus/multus.go

This change adds ConfList check in get delegates from cache, to delete network gracefully.

Check ConfList in delete network by cache

---

build

* `CGO_ENABLED=0` will create statically linked binaries (nice for the go binary running on the host machine and not in the container as is the case with Multus)
* `-tags no_openssl` will use the Go compiler's native cryptography without a reliance on OpenSSL.

[build] Adds CGO_ENABLED=0 and -tags no_openssl to build script

---

images/entrypoint.sh

Example:
```
2019-05-09T15:41:20-05:00 Generating Multus configuration file ...
2019-05-09T15:41:20-05:00 Attemping to find master plugin configuration, attempt 0
2019-05-09T15:41:20-05:00 Attemping to find master plugin configuration, attempt 1
2019-05-09T15:41:20-05:00 Attemping to find master plugin configuration, attempt 10
2019-05-09T15:41:20-05:00 Attemping to find master plugin configuration, attempt 15
2019-05-09T15:41:20-05:00 Attemping to find master plugin configuration, attempt 20
2019-05-09T15:41:20-05:00 Config file created @ /host/etc/cni/net.d/00-multus.conf
{ "name": "multus-cni-network", "type": "multus", "namespaceIsolation": true, "logLevel": "verbose", "kubeconfig": "/etc/kubernetes/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "cniVersion": "0.3.1", "name": …
```

entrypoint.sh: add timestamps to log messages; log autogenerated config file

---

doc/how-to-use.md
images/entrypoint.sh

Basically the gist behind this is that when using the autoconfiguration option, this gives an option to store those configurations in an alternate directory. 
This is useful for cases where you need finer grained control of when you denote that the node is ready or not (as advertised by the Kubelet when a CNI configuration is present)
The initial impetus for this is that with openshift-sdn, we need to both wait that openshift-sdn is fully initialized, and we do not want to launch any pods on a particular before our Multus configuration is in place (but only after openshift-sdn is fully initalized).

Adds --multus-autoconfig-dir and entrypoint documentation

---

types/conf.go
types/conf_test.go

This allows host-device plugin to recognize
Device PCI address passed from Multus.
It is related to the change in host-device which
enables use of device pci address as a config option:
https://github.com/containernetworking/plugins/pull/300

assign device id to pciBusID in delegated config

---

multus/multus.go

K8s with docker runtime, cmdDel() is invoked with empty network
namespace in case of restart node. Currently multus just returns
but CNI spec mention that we should invoke CNI plugin to cleanup.
This PR deletes "return nil" and proceeds to invoke CNI plugins
DEL. Fix #323.

Continue to process cmdDel() in case of no network namespace

---

doc/how-to-use.md
images/entrypoint.sh
multus/multus.go

This change introduces two fix about CNIVersion. One is to add CNIVersion into
delegated CNI conflist in case of DEL if CNIVersion is missing. ParseVersion() in libcni
checks cniVersion as mandatory field and sometimes user/daemonset miss it.
The latest flannel daemonset yaml (of flannel github) does not have CNIVersion, for example.
This change adds CNIVersion from multus config if cniVersion is missing (empty) in delegated
CNI config.
In addition, this fix also adds '--cni-version' in entrypoint.sh to add cniVersion in multus
config in case of '--multus-conf-file=auto'.

CNIVersion fix for conflist

---

images/entrypoint.sh
images/multus-daemonset-crio.yml

This change introduces multus-daemonset-crio again to support crio.
The change also introduce '--override-network-name' to use previous
master name in CNI json for multus CNI json.
Fix #325

Add daemonset for crio again

---

doc/how-to-use.md
types/conf.go

What I've done:
- Update docs to use new `interface` property
- Implement Unmarshaler that honors `interfaceRequest` alternatif to `interface`
Fix https://github.com/intel/multus-cni/issues/294

Support pre v3.2 "interfaceRequest"

---

doc/how-to-use.md
images/entrypoint.sh
images/multus-daemonset-crio.yml

When using CRIO, you may wish to have the CNI config file that's used as the source for `--multus-conf-file=auto` renamed. This boolean option when set to true automatically renames the file with a `.old` suffix to the original filename.
Adds new option:
```
--rename-conf-file=true
```
Includes docs and addition to the CRIO daemonset.
Tomo has also recently noted, and I agree -- that the number of options is expanding rapidly, and we are incurring some overhead in having the entrypoint be a bash script. For future consideration.

[entrypoint] Adds script parameter to optionally rename source CNI with .old

---

.travis.yml
Dockerfile.openshift

Updates the `Dockerfile.openshift` to use `ENV GO111MODULE=off`
Additionally, adds a build from the Dockerfile.openshift to the travis build so that we get some feedback if it breaks (which it unfortunately did with #368)

Use ENV GO111MODULE=off when building from openshift/origin-release:golang-1.10

---

multus/multus.go

Appends binDir to CNI_PATH so that invoke.DelegateAdd/Del can find CNI plugins in alternate paths
@s1061123 can you take a look at this? I feel like this is a ham-fisted (that is, not elegant) way of doing this by explicitly setting CNI_PATH. Feels like I am doing something wrong. Do you think there's another way to approach this?
Currently, if you set `binDir` in the configuration, like:
```
{ "name": "multus-cni-network", "type": "multus", "binDir": "/opt/multus/bin/", "logLevel": "debug", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "cbr0", "plugins": [ { "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true } }, { "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }
``` …

Appends binDir to CNI_PATH 

---

doc/quickstart.md
images/multus-daemonset-crio-pre1.16.yml
images/multus-daemonset-crio.yml
images/multus-daemonset-pre-1.16.yml
images/multus-daemonset.yml

A few issues here...
* We will need to update the referenced image tag in the daemonset, as this plans to use the `--cni-version=` flag which isn't available in the `v3.2` tag.
* This is a WIP as I'm still experiencing some issues...
Primarily somehow the generated delegates isn't looking exactly perfect, we're hitting this error when we spin up a pod...
```
Events:
Type     Reason                  Age        From                             Message
----     ------                  ----       ----                             -------
Normal   Scheduled               <unknown>  default-scheduler                Successfully assigned default/samplepod to kube-singlehost-master
Warning  FailedCreatePodSandBox  4s         kubelet, kube-singlehost-master  Failed create pod sandbox: rpc error: …
```

[WIP] Updates daemonset for Kube 1.16, also docs and adds pre-1.16 daemonset

---

k8sclient/k8sclient.go
multus/multus.go
multus/multus_test.go
types/conf.go
types/conf_test.go
types/types.go

This changes introduce CNI RuntimeConfig for portmap, bandwidth, ip and mac for latest net-attach-def specification. IP and Mac is previously applied through CNI_ARGS, but it is changed to RuntimeConfig for now.

Support CNI RuntimeConfig for portmap/bandwidth/ip/mac

---

build

Previously the build script required git to be used and installed which
did not allow to build Multus from a tarball which doesn't contain .git
directory. That made packaging of Multus hard.
Example usage after the change if you do not want to use git:
```
$ VERSION=v3.3 COMMIT=ba33df ./build
```
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

build: Allow to define VERSION and COMMIT without git

---

multus/multus.go

Helps when debugging messages like:
```
Nov 05 17:43:29 ip-10-0-136-174 crio[1881]: 2019-11-05T17:43:29Z [error] Multus: error adding pod to network "ovn-kubernetes": delegateAdd: error invoking DelegateAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: 'Nil response to CNI request
```
Signed-off-by: Dan Williams <dcbw@redhat.com>
@dougbtv @s1061123

multus: print pod namespace/name in cmdAdd/cmdDel error messages

---

doc/how-to-use.md
images/entrypoint.sh

Adds option:
```
--skip-multus-binary-copy=
```
Allows you to skip having the binary copied via the entrypoint script. Useful in situations where other procedures need to copy a specific Multus binary.

Adds option to skips binary copy in entrypoint

---

images/entrypoint.sh

Issue:
/etc/cni/net.d/multus.d/multus.kubeconfig is not properly setup for IPv6
installs
Change Summary:
If the API server host is IPv6 address then the server URL should
include square braces to separate the IP address and port correctly
Signed-off-by: shravan@robin.io

Multus kubeconfig is not correct for IPv6 Installs

---

images/entrypoint.sh

Previously could leave unfinished write on config file while Multus is processing the config file.

Uses atomic operation for writing config file

---

.travis.yml

This change introduces multi architecture image by adding manifest for 'nfvpe/multus:latest' and 'nfvpe/multus:snapshot', like that https://hub.docker.com/repository/docker/s1061123/multus/tags?page=1
This change also parameterized container image registry name, as well as username/pass, hence this allows cloned repository to use travis.yml in their CI.

Support container multi architecture image with manifest

---

doc/quickstart.md

Was previously using `dougbtv/centos-network`, but, Alpine has the `ip` command which is all that we need for the quickstart examples (and the image size is much much smaller)

[docs] Updates quickstart to use alpine image

---

doc/how-to-use.md
images/entrypoint.sh
multus/multus.go

and exposes readinessindicatorfile via entrypoint parameter.
Generally, the idea is that if we're using the ExponentialBackoff while pods are crashlooping, we're not actually saving any time. Using a poll instead allows us to pick up more quickly than Kubernetes itself does (since it's already waiting on the backoff)

Changes wait.ExponentialBackoff to wait.PollImmediate

---

multus/multus.go

In cmdCheck and cmdDelete debug messages are logged even before logger
is initialized with its log level and file (done in types.LoadNetConf).
Because of this those debug messages are not logged into the file.
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

Log message after logger initialization

---

types/conf.go
types/conf_test.go

Until today, it was hardcoded that DeviceID will only be
injected for the first CNI in the chain.
This commit modifies multus to pass DeviceID to each network
configuration element in a network configuration list.
This will  allow multiple CNI's to act on DeviceID when CNI
plugins are being chained for a specific network.
The change is required to allow CNI's to ensure network
isolation (introduced in kernel >= 5.2.0 see [1]) for RDMA devices
when exist.
e.g for SR-IOV network:
sriov-cni moves network device associated with the provided DeviceID
to to the container's network namespace.
An "RDMA cni" would do the same for the corresponding RDMA device when
RDMA traffic is desired on the network.
[1] https://patchwork.kernel.org/cover/10810451/

Pass DeviceID to each plugin in configuration list

---

go.mod
go.sum
k8sclient/k8sclient.go
multus/multus.go
testing/testing.go
types/conf.go

This change adds pod UID and net-attach-def name in verbose log
and sends kubernetes event when net-attach-def is not found.

Logging improvement (UID, net-attach-def)

---

images/multus-daemonset-crio-pre1.16.yml
images/multus-daemonset-pre-1.16.yml

This was broken during the improvement for descriptions.

Fix pre 1.16 api version for CRDs

---

Dockerfile

I happened to notice that go-repo.io has 1.13 packages, took a look through `yum search golang --showduplicates
```
$ yum search golang --show-duplicates | grep "golang-1.13"
golang-1.13-0.el7.x86_64 : The Go Programming Language
golang-1.13.1-0.el7.x86_64 : The Go Programming Language
golang-1.13.2-0.el7.x86_64 : The Go Programming Language
golang-1.13.3-0.el7.x86_64 : The Go Programming Language
golang-1.13.4-0.el7.x86_64 : The Go Programming Language
golang-1.13.5-0.el7.x86_64 : The Go Programming Language
golang-1.13.6-0.el7.x86_64 : The Go Programming Language
golang-1.13.7-0.el7.x86_64 : The Go Programming Language
golang-1.13.8-0.el7.x86_64 : The Go Programming Language
golang-1.13.9-0.el7.x86_64 : The Go Programming Language
golang-1.13.10-0.el7.x86_64 : The Go Programming …
```

Updates Dockerfile to golang 1.13 (specifying version)

---

multus/multus.go

Fixes #481 
Here is the tip of stack trace:
```
Apr 16 19:03:00.175064 ci-op-nqdgf-m-0.c.openshift-gce-devel-ci.internal crio[1370]: 2020-04-16T19:03:00Z [verbose] Add: openshift-console:downloads-dc9498995-p4vgn:unknownUID:(openshift-sdn):eth0 {"cniVersion":"0.3.1","interfaces":[{"name":"eth0","sandbox":"/proc/20411/ns/net"}],"ips":[{"version":"4","interface":0,"address":"10.129.0.18/23"}],"routes":[{"dst":"0.0.0.0/0","gw":"10.129.0.1"},{"dst":"224.0.0.0/4"},{"dst":"10.128.0.0/14"}],"dns":{}}
Apr 16 19:03:00.177321 ci-op-nqdgf-m-0.c.openshift-gce-devel-ci.internal crio[1370]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 16 19:03:00.177321 ci-op-nqdgf-m-0.c.openshift-gce-devel-ci.internal crio[1370]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 …
```

Check Pod parameter against nil before calling Eventf

---

k8sclient/k8sclient.go

Lets pods fail in a somewhat reasonable amount of time if the API server is unavailable.

Sets the Kubernetes API calls timeout to 60 seconds

---

README.md

Minor typo error, a single character to `s/you/your/`

README typo for roll-YOUR-own

---

multus/multus.go
multus/multus_test.go
types/conf.go

This fix changes network status name to net-attach-def name with
namespace, to compliant with k8s npwg's multi-net-spec.

Fix network status name/namespace to compliant with multi-net-spec

---

k8sclient/k8sclient.go
types/conf.go
types/conf_test.go
types/types.go

This PR add support for a new CNI runtime config attribute
`InfinibandGUID` CNI runtime config which was introduced in [PR 742](https://github.com/containernetworking/cni/pull/742)
the corresponding network-attachment attribute is proposed to be defined as `infiniband-guid`
and discussed in [multi-net-spec PR 4](https://github.com/k8snetworkplumbingwg/multi-net-spec/issues/4)
A CNI implementation consuming this runtime config attribute (and can be used as reference) is proposed in [ib-sriov-cni PR 28](https://github.com/Mellanox/ib-sriov-cni/pull/28)

Support Infiniband guid CNI runtime config

---

build

This change will enable builds to be performed with the option of
passing the -mod flag to 'go build'. This can be done by optionally
setting the MODMODE environment variable prior to building.
For example, toggling the -mod setting for the build can be
accomplished as follows:
```
$ MODMODE=vendor ./build
```
Signed-off-by: Ryan Tidwell <rtidwell@suse.com>

build: Enable -mod build flag to be toggled via environment variable

---

build

Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This `date` call only works with GNU date (probably not a problem since kubernes is pretty Linux-specific).
Also use UTC to be independent of timezone.

Allow to override build date with SOURCE_DATE_EPOCH

---

images/multus-daemonset-crio.yml
images/multus-daemonset.yml

With patch:
```
[centos@kube-master1 ~]$ kubectl explain net-attach-def
KIND:     NetworkAttachmentDefinition
VERSION:  k8s.cni.cncf.io/v1
DESCRIPTION:
NetworkAttachmentDefinition is a CRD schema specified by the Network
Plumbing Working Group to express the intent for attaching pods to one or
more logical or physical networks. More information available at:
https://github.com/k8snetworkplumbingwg/multi-net-spec
FIELDS:
apiVersion	<string>
APIVersion defines the versioned schema of this representation of an
object. Servers should convert recognized schemas to the latest internal
value, and may reject unrecognized values. More info:
https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
kind	<string>
Kind is a string value representing the REST …
```

Fix CRD yaml file for right explan information

---

images/entrypoint.sh

As discussed in issue #544 the nested plugin `capabilities` are not integrated in the `00-multus.conf` file generated by the `images/entrypoint.sh` file.
I implemented the parsing of the underlying master plugin json configuration file with python, to retrieve the nested capabilities and to integrate them in the top-level section of the `00-multus.conf` file (because it is not sufficient to have capabilities declared in the `delegates` section of the CNI config file.)
The python script for analyzing underlying plugins capabilities is compatible with Python 2 and Python 3, it could be a bit shorter if I used only Python 3 syntax, but I noticed that the Dockerfile is based on a CentOS version that uses Phyton 2.
When no capabilities in the underlying plugins, then nothing gets added to the …

Pull underlying capabilities up to 00-multus.conf

---

images/multus-daemonset-crio.yml
images/multus-daemonset-gke-1.16.yml
images/multus-daemonset.yml

This fix supplies domain for container image repo because
in some runtime configuration, 'docker.io' is not specified as
default container repository url.

Specify image repo URL explicitly

---

.github/workflows/go-build-arm64.yml
images/multus-daemonset-crio.yml
images/multus-daemonset.yml

Adds ARM64 support for Multus re-using the existing
strategy used to add ppc64le support in previous iterations.
Fixes #554

Add ARM64 support

---

multus/multus.go

it can happen that a CNI Add operation is canceled because the
runtime sends a CNI Del too fast, so the pod was already deleted
when multus try to set the network status annotations.
Since multus is an executable and can not persist state, it can't
track the CNI requests that are done in parallel, but it can
assume that, if it was able to get the pod from the API, and in a
subsequent request the pod no longer exists, it is because it was
deleted.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
An example of the error is here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/4361/pull-ci-cri-o-cri-o-master-e2e-gcp/1329161665811320832
> ns/e2e-deployment-9487 pod/webserver-57656d96fb-4r4l5 node/ci-op-qpgcdqxr-3caf3-zl879-worker-b-lx77w - 5.31 seconds after …

clarify cmdAdd error

---

multus/multus.go

Otherwise, this can cause a pod to not be fully deleted, its sandbox may remain as the DEL continues to be retried due to exiting non-zero every time.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1900835

Multus should exit zero on DEL when cache file is missing and pod cannot be found.

---

doc/configuration.md
doc/how-to-use.md
images/entrypoint.sh
k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
types/conf.go
types/conf_test.go
types/types.go

When using `namespaceIsolation` -- we have only allowed for referring to the `default` namespace from any given namespace. This enhancement adds a configuration option `globalNamespaces` which allows one to specify any additional namespaces which they would like to refer to "globally" -- that is, from any given namespace (as opposed to "locally" -- from the same namespace in which a pod resides, which is the core functionality of `namespaceIsolation`).
The `globalNamespaces` parameter works only when `namespaceIsolation` is set to true. When `globalNamespaces` is unset, it is implied that `default` will still be allowed globally.
cc: @rohan47
Fixes #567

Allows specifying "global namespaces" when using namespace isolation

---

multus/multus.go

In
https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ,
section 4.1.2.1.9,
"
4.1.2.1.9 “default-route” Default route selection for a particular attachment
This optional key with value of type string-array is used to explicitly select
which attachment will receive the default route. The value of items in the
“default-route” array are intended to be gateways, e.g. an IP address to which
packets that do not match any other routes are sent. This key must only be set
on one item in the Network Attachment Selection Annotation. This list may be empty.
"
However en empty list will fail currently; this change accommodates an
empty "default-route" by retaining the default route added by the
delegate.
Signed-off-by: venugopal iyer <venugopali@nvidia.com>

Allow the default-route to be empty

---

images/entrypoint.sh

entrypoint script fails with error when try reading capabilities in
non chain plugin config file when using "--multus-conf-file=auto"
Fixes #594

Fix entrypoint fail to read capabilities in non chain plugin config

---

images/multus-daemonset-crio.yml
images/multus-daemonset.yml

Otherwise, it can take a long time for the daemonset to stop, and there's no real reason it needs to hang out for a long time.

Pods in daemonset should have grace period reduced.

---

images/entrypoint.sh

In my tests this improved the time to `kubectl delete pod $multus-daemonset-pod -n kube-system` by 5 seconds.
@s1061123 -- I had to use `wait` instead of `read` -- if I use `sleep $x & read` it waits for input before continuing, there is one spot where we sleep infinity, however, in a number of other spots we sleep inside a loop.

Adds a trap for SIGTERM in entrypoint script

---

pkg/types/conf.go
pkg/types/conf_test.go

When we call mergeRuntimeConfig, the global RuntimeConfig gets
overwritten with the result of the merging, thus affecting the
subsequent delegates.
Do not modify the global RuntimeConfig and instead make a copy
when merging it
Also, if a value has been provided for CNIDeviceInfoFile in the
delegate's runtimeconfig, overwrite it to avoid possible name
colissions.
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
Signed-off-by: Billy McFall <bmcfall@redhat.com>

conf: do not modify global runtimeconfig when merging

---

.github/workflows/docker-build-push-master.yml
.github/workflows/docker-build-push-release.yml
.github/workflows/docker-build.yml
.github/workflows/go-build-s390x.yml
deployments/Dockerfile.s390x
images/entrypoint.sh
images/multus-daemonset-crio.yml
images/multus-daemonset.yml

This PR updates the GitHub Actions workflows to build multus
container images for the IBM Z architecture (s390x), and also
adds daemonsets for s390x nodes.
entrypoint.sh uses python3 when it is available, since centos images
are not available for s390x, and python2 is not installed by default
on debian-based images.
Signed-off-by: Yohei Ueda <yohei@jp.ibm.com>

Add s390x support

---

images/entrypoint.sh

Conditional check for tty/non-tty in case of wait (i.e. read)

---

README.md

Re-adding NPWG slack invite mechanism.
Signed-off-by: Kennelly, Martin <martin.kennelly@intel.com>
I misunderstood slacks invite mechanism for non-Intel users. Non-Intel users require invite it seems. Re-adding invite mechanism. I attempted to change URL of invite mechanism but failed. Slack only grands auto invite rights to enterprise workspaces. See here https://github.com/outsideris/slack-invite-automation/issues/146
Currently, the intel-corp.heroku.com app relies on legacy token mechanism to accomplish this. This will fail in the future when legacy tokens are deprecated. I think this should be discussed at NPWG level but in the mean time, I propose re-adding auto invite mechanism. Thanks @s1061123  for highlighting this!

Fix invite to NPWG slack

---

docs/configuration.md
images/entrypoint.sh
pkg/types/conf.go
pkg/types/types.go

Today, Multus will always log via STDERR, and these logs will then
logged by the Kubelet. If we also choose to have Multus log to a file by
setting the LogFile option in the CNI configuration, the same logs will
be logged twice.
This commit provide the option to disable logging to STDERR.
Signed-off-by: Yun Zhou <yunz@nvidia.com>

Provide the option to not to log via STDERR

---

pkg/multus/multus.go
pkg/multus/multus_test.go

This changes CNI cache directory to non default places to avoid conflicts among CNI runtimes.

Change libcni's cache directory from default for multus delegates

---

pkg/multus/multus.go
pkg/types/conf.go

The case withot DeviceInfo/ResourceName, we could skip functions
related to device info. This change skips to call these functions
if delegates does not have DeviceInfo/ResourceName.

Skip to call device-info related function if not required

---

.github/workflows/image-build.yml
.github/workflows/image-push-master.yml
.github/workflows/image-push-release.yml
deployments/Dockerfile.arm32

Currently multus-cni releases arm32 binary as release tar ball.
This changes also introduce container image for easy deployment.
Fix #639

Add arm32v7 container image support

---

e2e/setup_cluster.sh

Setting up for manual e2e-tests fails due to that the multus container image is not built. This works fine in CI since this part is done separately within the github action.
This is a minor change to use the new location of the Dockerfile when running the e2e-tests manually.

Correcting Dockerfile path for manual e2e tests

---

docs/configuration.md

This PR adds description about a condition that needs to be satisfied when configuring `clusterNetwork` to refer to a CNI JSON config file in `confDir`. I was trying to use `clsuterNetwork` config, but failed for a while as the file name set for `clusterNetwork` didn't match the value for `name` key in the file. It would be helpful to describe the condition currently undocumented.

Describe additional condition when using clusterNetwork

---

images/README.md

The calico's master branch structure has updated, the url is invalid.

Update calico daemonset's url

---

pkg/kubeletclient/kubeletclient.go

Signed-off-by: Peng Liu <pliu@redhat.com>

Use the default socket path in GetResourceClient when unspecified

---

pkg/multus/multus.go

Use exponential backoff when retrying to retrieve the pod for both ADD/DEL commands.
The retries occur when getting the pod information fails with either of the following errors:
- service unavailable
- server internal error
- connection reset
- connection refused
Fixes: https://github.com/k8snetworkplumbingwg/multus-cni/issues/649

Retry on multiple error types with backoff

---

deployments/Dockerfile

Addresses #693 
Before change, docker build would fail with following error
```
#7 567.3 go: github.com/k8snetworkplumbingwg/network-attachment-definition-client@v1.1.1-0.20210510153419-66a699ae3b05 requires
#7 567.3  k8s.io/code-generator@v0.18.3 requires
#7 567.3  golang.org/x/mod@v0.3.1-0.20200828183125-ce943fd02449: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/13df7481b5cc3358460b717a6142fe8dbaae7652e5d05689849f419ffd40ac12: exit status 128:
#7 567.3  fatal: git fetch-pack: expected shallow list
------
executor failed running [/bin/sh -c rpm --import https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO &&     curl -s https://mirror.go-repo.io/centos/go-repo.repo | tee /etc/yum.repos.d/go-repo.repo &&     yum install -y $INSTALL_PKGS &&     rpm -V …
```

Update golang version for installing packages

---

images/entrypoint.sh

Before change, specifying MULTUS_MASTER_CNI_FILE_NAME would not properly generate multus conf as the file path was wrong 
Multus pod logs would show following error
```
kubectl logs -f pod/kube-multus-ds-8zs2t -n kube-system
2021-07-12T16:50:00+0000 Generating Multus configuration file using files in /host/etc/cni/net.d...
2021-07-12T16:50:00+0000 Using MASTER_PLUGIN: /host/etc/cni/net.d/10-aws.conflist -> this should take only filename and not entire path 
cat: /host/etc/cni/net.d//host/etc/cni/net.d/10-aws.conflist: No such file or directory -> Incorrect file path 
Traceback (most recent call last):
File "/tmp/tmp.zngU7gWnzK", line 2, in <module>
conf = json.load(sys.stdin)
File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
**kw)
File …
```

Use MULTUS_MASTER_CNI_FILE_NAME as MASTER_PLUGIN as is, if specified

---

.github/workflows/build.yml
.github/workflows/test.yml
deployments/Dockerfile
deployments/Dockerfile.arm32
deployments/Dockerfile.arm64
deployments/Dockerfile.openshift
deployments/Dockerfile.ppc64le
deployments/Dockerfile.s390x

Currently golang community supports 1.16 and later, hence, need
to update golang version in our build pipeline. This change
updates golang version to 1.17/1.16.

Update golang version (at least >= 1.16)

---

.github/workflows/legacy-kind-e2e.yml
e2e/legacy-multus-daemonset.yml
e2e/setup_cluster.sh

Our CI is currently mistakenly executing the thick img on the e2e
legacy lanes. Furthermore, the e2e daemonset spec provided features
(and uses) the kubeconfig / multus conf generation binaries
provided only on the thick image.
This commit addresses these by enabling the e2e `setup_cluster.sh`
script user to specify the path to the desired deployment
configuration.
Github workflows are updated accordingly.
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>

CI, e2e tests: fix legacy

---

pkg/config/manager.go
pkg/config/manager_test.go

The test was just checking that a READ/WRITE `fsnotify.Event` for
the multus configuration was being seen; this patch changes this
behavior, and assures that the delegateCNI configuration update results
in turn on the update of the multus configuration file.
The multus tmp directory for the CNI configuration is also updated.
Fixes: #756

flaky: fix delegate CNI conf updates unit test

---

pkg/k8sclient/k8sclient.go
pkg/multus/multus.go
pkg/netutils/netutils.go
pkg/netutils/netutils_test.go
pkg/types/conf.go
pkg/types/types.go

To keep consistency between actual network and CNI result in cache, update libcni cache when multus add/del default routes by
`default-route` network selection.

Update libcni cache when default-route net selection is used

---

deployments/multus-daemonset-crio.yml
deployments/multus-daemonset-gke-1.16.yml
deployments/multus-daemonset-thick-plugin.yml
deployments/multus-daemonset.yml

This PR adds toleration against NoExecute for `kube-multus-ds` DaemonSet. I think it's a common practice for CNI plugins to set tolerations against `NoSchedule` and `NoExecute` as well.
The final goal of this PR is to include the toleration in the release manifest like https://github.com/k8snetworkplumbingwg/multus-cni/blob/v3.8/images/multus-daemonset.yml, but I'm not so sure the files changed in this PR are right to do that. If my guess is wrong, could you let me know where the right location is?

Add toleration against NoExecute

---

e2e/multus-daemonset.yml

On the e2e tests you cannot send events since the service account does not have enough permissions.

multus, e2e tests: allow event sending to k8s API

---

e2e/multus-daemonset.yml

Currently, the local workflow is far from optimal, since for every
change on the multus images the developers are required to redeploy
the kind cluster.
A more efficient workflow would be to build a local image, upload it to
the kind cluster, and finally re-deploy (delete & re-provision) the
daemonset, which would be running the new version.
For this flow to be possible, the multus container `imagePullPolicy`
must be set to `Always` - [0] - otherwise, the image is not updated.
To use this flow, execute the following commands:
```bash
$ hack/build-go.sh
$ podman build -t localhost:5000/multus:e2e -f images/Dockerfile.thick .
...
$ podman push localhost:5000/multus:e2e
Getting image source signatures
Copying blob 2007419be463 done  
Copying blob 6f64ff3fc38f done  
Copying blob e7ed17121dee …
```

e2e tests: always pull new multus images

---

pkg/multus/multus.go
pkg/multus/multus_test.go
pkg/types/conf.go
pkg/types/conf_test.go

setenv refers environment variables, which is unique in process,
not unique to go routine. Hence it may causes some issue in multi
threaded case, hence it is replaced with libcni's runtimeConfig
value set to set these variables at libcni side, after process
fork.

Replace setenv with runtimeConfig set

---

cmd/controller/main.go
go.mod
images/entrypoint.sh
pkg/config/generator.go
pkg/config/generator_test.go
pkg/config/manager.go
pkg/config/manager_test.go
vendor/modules.txt

When nested CNI version is 0.3.1 or less while the top level CNI version
is 0.4.0, error out. Version 0.3.1 or less doesn't support the CHECK
command. This closes issue #737.

check version incompatibility

---

deployments/multus-daemonset-crio.yml

to prevent "unknown FS magic on "/var/run/netns/*": 1021994" errors
Signed-off-by: Peter Hunt <pehunt@redhat.com>

crio: mount /run rslave

---

pkg/multus/multus.go

In cmdDel, CNI Spec mentioned that plugin should proceed cmdDel without any error, hence the change removes error returning
at cmdDel.
fix #822

Remove error handling for getPod to force to proceed cmdDel.

---

e2e/cni-install.yml
e2e/get_tools.sh

Hi, I noticed that some of the tools are a bit out of date,So I update these tools version:
- cni-plugins: v0.8.5 -> v1.1.1
- kind: v0.8.1 -> v0.12.0
- koko: v0.82 -> v0.83

update e2e tools version for kind and cni-plugins

---

pkg/multus/multus.go

Should say `CheckNetwork` instead of `DelNetwork`

Fixes log message on CNI Check

---

deployments/multus-daemonset-thick.yml
pkg/checkpoint/checkpoint.go
pkg/checkpoint/checkpoint_test.go
pkg/multus/multus.go

Fix thick plugin daemonset to add volume mapping required for
sr-iov and fix code to update network status.
In addition, fix checkpoint structures to support K8s without
kubelet pod resources API.
fix https://github.com/k8snetworkplumbingwg/multus-cni/issues/665 and https://github.com/k8snetworkplumbingwg/multus-cni/issues/778

Fix sr-iov support

---

pkg/types/conf.go
pkg/types/conf_test.go

strings.Split() returns a slice, in this case with two elements of
the key and value. As such we shouldn't range over the slice when
the code is expecting a 2-element slice of key/value.
Otherwise we get errors for valid CNI_ARGS like:
```
2022-04-22T11:53:54Z [error] CreateCNIRuntimeConf: CNI_ARGS K8S_POD_NAMESPACE=openshift-etcd K8S_POD_NAMESPACE 17 is not recognized as CNI arg, skipped
2022-04-22T11:53:54Z [error] CreateCNIRuntimeConf: CNI_ARGS K8S_POD_NAMESPACE=openshift-etcd openshift-etcd 14 is not recognized as CNI arg, skipped
```
Fixes: d7d2a99ab5b8 ("Replace setenv with runtimeConfig set")
@s1061123 @dougbtv

types: fix usage of strings.Split() for parsing CNI_ARGS

---

pkg/multus/multus.go

It was previously using the net-attach-def name, which doesn't align with the cache file. Causing default-route selection to not succeed.
To reproduce the error, run through the steps in [the specifying a default route docs](https://github.com/k8snetworkplumbingwg/multus-cni/blob/130db696ca739fb3bcb550104ace34f03c00a360/docs/how-to-use.md#specifying-a-default-route-for-a-specific-attachment).
Previous to this fix, it should fail with:
```
error deleting default gateway in cache: open /var/lib/cni/multus/results/macvlan-conf-1b516b1ef0c52920145b3502a71182c92858a542067ea1f134d0dcd27e61f3c4-net1: no such file or directory
```
In this case the string `macvlan-conf` comes from the net-attach-def name, but it should come from the delegate name in order to match the cache filename on disk.

The cachefile name should be the delegate configuration name

---

images/README.md

This PR fixes an outdated reference in the docs where
multus-daemonset.yml was expected to be found under the images folder.

Fix wrong location for daemonset in readme

---

go.mod
go.sum
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
vendor/modules.txt

This accounts for CNI v1.0 formatted IP address information (no longer requires version field)

Bumps net-attach-def client library to v1.1.1

---

docs/how-to-use.md

This may make it easier for users to find info on logging parameters since there isn't a dedicated docs page for it.

Added hyperlink for logging

---

docs/configuration.md

The logging parameters were listed using uppercase, which is wrong. 
According to multus configuration, they should be in camelCase:
- [logFile]( https://github.com/k8snetworkplumbingwg/multus-cni/blob/779170a48ea767fe367f58ca472a8c403c203c6f/pkg/types/types.go#L45)
- [logLevel](https://github.com/k8snetworkplumbingwg/multus-cni/blob/779170a48ea767fe367f58ca472a8c403c203c6f/pkg/types/types.go#L46)

config, logging: correct the logging parameters

---

pkg/multus/multus.go

Fixed the possibility that in.Delegates may remain in the CmdDel method when the Pod does not use the cluster network.
For example:
If the cluster network is of type `conflist`, the network specified by `v1.multus-cni.io/default-network` in the Pod is of type `conf`.  The following code will have a problem：
```Go
if err := json.Unmarshal(netconfBytes, &in.Delegates); err != nil {
return cmdErr(k8sArgs, "failed to load netconf: %v", err)
}
```
`Umarshal` will not clear the existing data in Delegates first. CmdDel will report an error:
2022-06-06T17:03:58+08:00 [error] conflistDel: error converting the raw bytes into a conflist: error parsing configuration list: no 'plugins' key
2022-06-06T17:03:58+08:00 [error] delegateDel: error invoking ConflistDel - "xxx": conflistDel: error converting …

Fixed that in.Delegates may remain in the CmdDel

---

pkg/multus/multus.go

This change skips to update pod's network-status annotation
when getPod is failed at the beginning of CmdDel. If getPod is
failed, K8s api gets stucked in many cases, hence pod update
might be failed in most cases.

Skip status update in CmdDel if getPod is failed

---

pkg/types/conf.go

When chained plugins are used, the networks-status annotations is missing the device-info section.
This PR aims to fix this.

Fix missing device-info in networks-status annotation for chained plugins

---

cmd/config-generation/kubeconfig.go

This change will make debugging easier in cases when non-default
location is used and user forgot to mount new directory.

write output file for generated kubeconfig

---

cmd/multus-daemon/main.go
cmd/multus-shim/main.go
docs/thick-plugin.md
pkg/multus/multus.go
pkg/multus/multus_cni020_test.go
pkg/multus/multus_cni040_test.go
pkg/multus/multus_cni100_test.go
pkg/server/api/api.go
pkg/server/api/doc.go
pkg/server/api/shim.go
pkg/server/api/socket.go
pkg/server/api/types.go
pkg/server/server.go
pkg/server/thick_cni_test.go
pkg/server/types.go
pkg/types/conf.go
pkg/types/types.go

This changes introduce delegate API function in multus-daemon.
This API will be consumed from other programs for hot-plug interface into running pod. This change also cleanups server code to split into client code and server code to easy to import from other golang code.

Add delegate API in multus-daemon

---

pkg/types/conf.go
pkg/types/conf_test.go

when the configuration specifies both an IPv4 and IPv6 default route,
the IsFilterV4Gateway and IsFilterV6Gateway flags should both be false,
to allow the gateway configuration.
The logic in CheckGatewayConfig would do the inverse, setting both to
true in case of both IPv4 and IPv6 gateway.
Fixes: d52f2b6a ("Update libcni cache when default-route net selection
is used")
Signed-off-by: Tim Froidcoeur <tim.froidcoeur@tessares.net>

fix multiple default gw

---

pkg/types/conf_test.go

Replaces the existing matchers by a more idiomatic approach, which return better error msgs when the test fails.
The following matchers are used:
- `BeTrue`
- `BeFalse`
- `HaveLen`
- `BeEmpty`
Furthermore, they make the test easier to read.

Idiomatic config unit tests

---

.github/workflows/image-push-release.yml
deployments/multus-daemonset-thick-plugin.yml

Due to #900, image tag, ':thick', which is used in 4.0 and 3.x, gets user confused because thick image is not compatible between 4.0 and 3.x. This fix provides strict version name in deployment yaml to specify install image tag.
Note: This requires to release v3.9.2 release, after the PR merge.

Fix release 3.x thick image tag to isolate from 4.0

---

pkg/kubeletclient/kubeletclient.go

The kubeletSocket in the function is scoping the const kubeletSocket which causing resource api to fail with
"stat /var/lib/kubelet/pod-resources/.sock: no such file or directory"
Signed-off-by: Moshe Levi <moshele@nvidia.com>

fix kubeletSocket scope

---

pkg/kubeletclient/kubeletclient.go
vendor/google.golang.org/grpc/credentials/insecure/insecure.go
vendor/modules.txt

see https://github.com/kubernetes/kubernetes/commit/2c8bfad9106039aa15233b5bf7282b25a7b7e0a0
Signed-off-by: Moshe Levi <moshele@nvidia.com>

grpc: move to use grpc.WithTransportCredentials()

---

docs/configuration.md
pkg/multus/multus.go
pkg/types/types.go

this case should try max to cleanup
sandBox container stop times, but delegated plugin failed (CNI server maybe in starting .... ) , but cache file has been deleted
container gc manager clean up forever even though POD has been fully deleted from ETCD
POD not find && cache file not find; never clean up, we should try max ...
Add an option allowTryDeleteOnErr in multus conf,   allow to try delegate message on such error  scene

delegate plugin delete success, delete cache file

---

pkg/kubeletclient/kubeletclient.go
pkg/kubeletclient/kubeletclient_test.go

After commit https://github.com/k8snetworkplumbingwg/multus-cni/commit/c6fa047212efc3a410fb73aa83d2594a4f914320 resource api got broken in 2 places. first place handled by https://github.com/k8snetworkplumbingwg/multus-cni/commit/f530d3eb84608fa25a59737bcf49991d4a037d82 The second break was in replacing podresources.GetV1Client with getKubeletResourceClient. The GetV1Client remove the protocol (e.g unix:) by calling GetAddressAndDialer, but the getKubeletResourceClient is using the full endpoint (with the portocol) causing failed to connect to unix socket. This patch remove the unix: prefix before the grpc connect.
Fixes: #944
Signed-off-by: Moshe Levi <moshele@nvidia.com>

fix resource api  grpc failed to connect to unix socket

---

pkg/checkpoint/checkpoint.go
pkg/checkpoint/checkpoint_test.go
pkg/k8sclient/k8sclient_test.go
pkg/kubeletclient/kubeletclient_test.go
pkg/logging/logging_test.go
pkg/multus/multus.go
pkg/multus/multus_cni020_test.go
pkg/multus/multus_cni040_test.go
pkg/multus/multus_cni100_test.go
pkg/netutils/netutils.go
pkg/server/api/api.go
pkg/server/config/generator.go
pkg/server/config/generator_test.go
pkg/server/config/manager.go
pkg/server/config/manager_test.go
pkg/server/server.go
pkg/server/thick_cni_test.go
pkg/testing/testing.go
pkg/types/conf.go
pkg/types/conf_test.go

We should clean all io/util package according the url: https://go.dev/doc/go1.16#ioutil
/kind cleanup

remove io/ioutil for advanced golang

---

pkg/multus/multus.go

This fix changes conditional flow to use net-attach-def if cache file is collapsed in CmdDel.
Fix #948

Change conditional flow to use cache file in CmdDel

---

pkg/server/api/api.go
pkg/server/server.go

From the node (or any privileged pod having mounted the multus socket) you can now query the multus-cni server liveliness - for instance:
```
root@kind-worker:/# curl -v --unix-socket /run/multus/multus.sock localhost/healthz
*   Trying /run/multus/multus.sock:0...
* Connected to localhost (/host/run/multus/multus.sock) port 80 (#0)
> GET /healthz HTTP/1.1
> Host: localhost
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 14 Nov 2022 17:21:07 GMT
< Content-Length: 0
< Connection: close
<
* Closing connection 0
```
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
Fixes: #970

server: add healthz endpoint

---

.github/workflows/image-build.yml

This change remove origin build from CI pipeline because origin's golang version is too old.

Remove origin from CI build

---

.github/workflows/image-build.yml
images/Dockerfile.openshift

This has a build against openshift origin, since the original image was out of date, this builds a golang builder image prior to the origin Multus build using the dockerfile provided by OKD.

Create an openshift origin (OKD) golang builder image in build pipeline

---

go.mod
go.sum
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
vendor/modules.txt

Update network-attachment-definition-client package to support DeviceInfo spec 1.1.0
Related PRs:
https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/pull/49
https://github.com/k8snetworkplumbingwg/device-info-spec/pull/3
network-attachment-definition-client v1.4.0 content: https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/releases/tag/v1.4.0

Update network-attachment-definition-client to v1.4.0

---

go.mod
go.sum
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
vendor/modules.txt

Update network-attachment-definition-client package to support DeviceInfo spec 1.1.0
Signed-off-by: Yury Kulazhenkov <ykulazhenkov@nvidia.com>

Update network-attachment-definition-client for multus v3 branch

---

cmd/multus-shim/main.go
cmd/multus/main.go
pkg/k8sclient/k8sclient.go
pkg/multus/multus.go

if bool variable is true , then we can omit it in ``` if xxx```

code clean for if condtion

---

deployments/multus-daemonset-crio.yml
docs/how-to-use.md
docs/thick-plugin.md
images/entrypoint.sh

'restart-crio' option was used for workaround crio issues. This issue no longer exists, hence make it obsolate and removed.

Remove deprecated 'restart-crio' option

---

go.mod
pkg/logging/logging.go

[https://github.com/pkg/errors](https://github.com/pkg/errors)  says : This repository has been archived by the owner on Dec 1, 2021. It is now read-only.
I suggest we should delete that , replaced by the go's error package.

Cleanup : github.com/pkg/errors has been archived.

---

.github/workflows/image-build.yml

This change remove origin build from CI pipeline because origin's golang version is too old.

Remove origin from CI build (for release-v3)

---

cmd/multus-daemon/main.go
deployments/multus-daemonset-thick.yml
e2e/templates/multus-daemonset-thick.yml.j2
pkg/server/api/shim.go
pkg/server/config/generator.go
pkg/server/server.go
pkg/server/thick_cni_test.go
pkg/server/types.go
pkg/types/conf.go
pkg/types/types.go

Adjust the user configuration to take place from a single place: the `configMap`.
Keeps only the bare minimum of command line options (in particular: where the config file lives, and the version flag).
Supersedes: #1006

Improve v4 config

---

deployments/multus-daemonset.yml

This change removes 'cni-version' option in entrypoint from default deployment manifest. This change uses cniVersion of delegate CNI, cluster network.

Remove 'cni-version' option in default deployment

---

cmd/multus-daemon/main.go
deployments/multus-daemonset-thick.yml
docs/thick-plugin.md
e2e/templates/multus-daemonset-thick.yml.j2
pkg/server/api/shim.go
pkg/server/server.go
pkg/server/thick_cni_test.go
pkg/types/conf.go
pkg/types/types.go

PR #1053 changed the thick plugin configuration to happen exclusively via the user provided config map.
This PR aligns the multus documentation with the existing code.
It also renames the multus socket dir configuration to something that does not stutter (daemon.DaemonSocketDir stutters).

docs, thick plugin: align docs with new configuration reference

---

pkg/kubeletclient/kubeletclient_test.go
pkg/multus/multus.go
pkg/multus/multus_suite_test.go
pkg/netutils/netutils.go
pkg/server/config/generator.go
pkg/server/server.go
pkg/server/thick_cni_test.go
pkg/server/types.go
pkg/types/conf.go

Fix linter/revive warning message.

Fix linter warning message

---

cmd/multus-daemon/main.go
deployments/multus-daemonset-thick.yml
pkg/server/config/generator.go
pkg/server/config/generator_test.go
pkg/server/config/manager.go
pkg/server/config/manager_test.go
pkg/server/server.go
pkg/server/types.go
pkg/types/conf.go
pkg/types/types.go

to damonset config file, hence command line option parsing is no longer used. This change removes these parts.
Fix #1058.

Refactoring thick daemon config processing

---

pkg/k8sclient/k8sclient.go
pkg/server/server.go
pkg/types/conf.go

Thick server's chroot mutex is missing in GetDefaultNetworks, that touch the pod filesystem. This change adds mutex lock there and prevent race condition.
Fix #1072

Add mutex lock for load confs in GetDefaultNetworks

---

pkg/multus/multus.go
pkg/multus/multus_cni020_test.go
pkg/multus/multus_cni040_test.go
pkg/multus/multus_cni100_test.go

This change fixes multus to support CNI plugin which does not create any interface and return empty result. Some CNI plugin may do network configuration change only and does not create any interface and return empty CNI result. Current multus assumes that CNI config always creates some interfaces hence above CNI plugin is out of assumption and multus may not work with such plugins.

Fix multus to support CNI plugin which does not create interface

---

cmd/multus-daemon/main.go
cmd/thin_entrypoint/main.go
cmd/thin_entrypoint/main_test.go
deployments/multus-daemonset-thick.yml
pkg/multus/multus.go
pkg/server/config/generator.go
pkg/server/config/manager.go

This changes refines parameters in multus thick/thin.
- delete unused parameter, confDir
- add multus-cni-conf-dir
- fix multusConfigPath in non-default params case

Refine and fix parameters

---

cmd/multus-daemon/main.go
pkg/multus/multus.go
pkg/server/config/manager.go
pkg/server/config/manager_test.go
pkg/server/server.go
pkg/types/conf.go

This change supports readinessIndicatorfile in multus-daemon and refines goroutine termination in case of signal with context.

Support readinessIndicator file in thick multus-daemon

---

hack/test-go.sh
pkg/logging/logging.go

This PR addresses the race conditions discovered during local testing using the Go race command. The race command detected potential data race conditions in the logging package's SetLogOptions and SetLogFile functions when multiple goroutines accessed and modified the shared logger struct concurrently.
Before applying the fix, the race detector logs indicated conflicting accesses as can be seen here:
```
WARNING: DATA RACE
Write at 0x00c000040d38 by goroutine 35:
[gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/logging.SetLogOptions()](http://gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/logging.SetLogOptions())
/home/asudakov/go/src/github.com/AlinaSecret/multus-cni/pkg/logging/logging.go:61 +0x6e4
[gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/types.LoadNetConf()](http://gopkg.in/k8s …
```

Fix race conditions in logging package functions and enable race detection in tests

---

cmd/thin_entrypoint/main.go

Check masterConfigPath file and skip if it is multus generated files. Fix #1130

fix multus config file generation to avoid self-delegation

---

.github/workflows/kind-e2e.yml

When things go wrong the logs can help figure out why.

github: export and upload e2e test kind logs

---

cmd/cert-approver/main.go
cmd/kubeconfig_generator/main.go
go.mod
hack/build-go.sh
images/Dockerfile
images/Dockerfile.debug
images/Dockerfile.thick
pkg/k8sclient/k8sclient.go
pkg/k8sclient/kubeconfig.go
pkg/multus/multus_cni100_test.go
pkg/server/server.go
pkg/server/types.go
vendor/k8s.io/client-go/tools/watch/informerwatcher.go
vendor/k8s.io/client-go/tools/watch/retrywatcher.go
vendor/k8s.io/client-go/tools/watch/until.go
vendor/k8s.io/client-go/util/certificate/OWNERS
vendor/k8s.io/client-go/util/certificate/certificate_manager.go
vendor/k8s.io/client-go/util/certificate/certificate_store.go
vendor/k8s.io/client-go/util/certificate/csr/csr.go
vendor/modules.txt

This change introduces per-node certification for multus pods. Once multus pod is launched, then specified bootstrap kubeconfig is used for initial access, then multus sends CSR request to kube API to get original certs for kube API access. Once it is accepted then the multus pod uses generated certs for kube access.
This PR only targets the code and doc/installer manifests will be addressed in another PR.

Add per-node-certification support

---

deployments/multus-daemonset-thick.yml
pkg/k8sclient/k8sclient.go
pkg/server/exec_chroot.go
pkg/server/exec_chroot_test.go
pkg/server/server.go
pkg/types/conf.go

We used to run chroot in multus main process when calling other CNI plugin binary. We also use a mutex to lock the access to pod files. But this causes performance issues when facing heavy CNI_ADD/CNI_DEL requests.
With this patch, we do chroot in the child processes instead. So file operations in the main process will not be affected by chroot.
This change requires the multus thick plugin pod to mount CNI bin directory to the same path in the container host.
fixes https://issues.redhat.com/browse/OCPBUGS-18995

Move chroot from multus main process to its child processes

---

cmd/kubeconfig_generator/main.go
pkg/k8sclient/kubeconfig.go
pkg/server/server.go
pkg/server/types.go

This change introduces certDuration as parameter to customize cert duration. In addition, environment variable for node name is matched to other usages.

Per node certificates: Add duration parameter

---

cmd/cert-approver/main.go
pkg/multus/multus.go

This change stops to update status in CNI's DEL command. There are two reasons:
1. cmd DEL is invoked at only pod deletion, hence k8s does not guarantee the pod and it may be already deleted. Hence this API may failed.
2. In stateful set's pod recreation case, it may have race condition to update the status at cmd DEL case.
In stateful set case, same pod name, i.e. stateful-0, is deleted and then created again. In this case, if old Pod's CNI DEL command is not finished before new Pod's creation, then SetStatus function is failed due to pod UID mismatch.

Suppress status unset in cmdDel

---

deployments/multus-daemonset-thick.yml

The ClusterRole was missing the watch permission on pods, which resulted in Multus throwing this error message every few seconds:
```
Failed to watch *v1.Pod: unknown (get pods)
```
I am unsure if this permission is also needed for the other 2 example yamls, so I've just added it to the one I tested for the moment.

Deployments: Add watch permission to thick example

---

docs/configuration.md

There's some backlog in here that needs to be addressed. 
This could probably use another pass in order to address the configmap as used in the thick plugin as well. However, at least this sets the stage for that change.

Refactors the configuration options document reference

---

e2e/templates/multus-daemonset-thick.yml.j2

As described in #1171, the watch function is required in the clusterrole for the thick Multus version, otherwise "Failed to watch *v1.Pod" would be returned.
This permission is still missing in `e2e/templates/multus-daemonset-thick.yml.j2`

Add watch permission to thick e2e template

---

docs/quickstart.md

The code repository is not cloned and the configuration is delivered directly

The code repository is not cloned and the configuration is delivered directly

---

cmd/thin_entrypoint/main.go

This change adds 1sec sleep for kubeconfig watch loop to prevent CPU high utlization.

Add additional sleep in thick entrypoint

---

pkg/k8sclient/kubeconfig.go

When user recreate whole cluster certs, multus thick plugin's previous cert is no longer valid. In such case, we need to prevent to use cert manager's old certs and restart it from bootstrap kubeconfig. This fix reloads client config from bootstrap kubeconfig if cert mgr's cert is failed to load pod.

Reload bootstrap kubeconfig if cert mgr failed to load valid certs

---

cmd/kubeconfig_generator/main.go
cmd/multus-daemon/main.go
pkg/server/api/api.go
pkg/server/config/manager.go
pkg/server/server.go

Uses `filepath.Abs()` to check that paths passed  in are truly absolute paths, and not garbage data (for example).

Add filepath sanity check

---

cmd/thin_entrypoint/main.go
cmd/thin_entrypoint/main_test.go

Changes how new kubeconfig is created after CA/token change. Instead of always creating new file on disk and comparing it to existing, it will compare base files (`ca.crt` and `token`) and recreate kubeconfig only if they changed.
Multus CNI config is now treated the same way - as base file the master cni config is used.
As a result `thin_entrypoint` will no longer create new kubeconfig and 00-multus on each iteration of the watch loop and only recreate them when underlying base files change.
This approach was chosen over using a fsnotify because it wasn't reliable watching `/var/run/secrets/kubernetes.io/serviceaccount/` - it would just stop noticing changes to files, possible reason is underlying filesystem being `tmpfs`.

Recreate configs only if base files changed (thin_entrypoint)

---

pkg/multus/multus.go
pkg/types/conf.go

Because deletes should favor a successful path, the readiness check should be skipped for pod removals.
This can cause an issue where there's pods pending deletes and that might impact scheduling of a pod that may be necessary in order to set the readiness indicator.

Skips checking for readiness on CNI DEL

---

pkg/server/server.go

On the CNI request failure, multus-cni prints out `cmdArgs`.  In all cases, except for debug printing, this is done with `%s` and a special printing function.  However, the `handleCNIRequest` is an exception for some reason.  That leads to unintelligible error messages in case of CNI request failures (severely abridged):
```
CmdAdd (shim): CNI request failed with status 400:
'&{ContainerID:<id> Netns:/var/run/netns/<uuid> IfName:eth0
Args:<args> Path: StdinData:[125 121 111 117 114 32 97 100 118
101 114 116 105 115 101 109 101 110 116 32 99 111 117 108 100
32 98 101 32 104 101 114 101 125 ... another 650 numbers ]}
ContainerID:"<id>" Netns:"/var/run/netns/<uuid>" IfName:"eth0"
Args:"<args>" Path:"" ERRORED: error configuring pod ...
```
`printCmdArgs()` should be used for this case as …

server: More concise error messages.

---

deployments/multus-daemonset-crio.yml
deployments/multus-daemonset-thick.yml
deployments/multus-daemonset.yml

Picked from suggestion @ https://github.com/openshift/multus-cni/pull/227/files
Change terminationMessagePolicy to FallbackToLogsOnError for enhanced error visibility, Kubernetes will use the last chunk of the container's log output as the termination message

Enforce termination message policy on all platform pods

---

pkg/multus/multus_cni020_test.go
pkg/multus/multus_cni040_test.go
pkg/multus/multus_cni100_test.go
pkg/server/thick_cni_test.go
pkg/types/conf_test.go

As https://github.com/k8snetworkplumbingwg/multus-cni/pull/98#issuecomment-413552685, 'defaultnetworkfile' should be 'readinessindicatorfile'.

Fix defaultnetworkfile in unit test

---

pkg/netutils/netutils.go
pkg/netutils/netutils_test.go

deleteDefaultGWResult() may create 'routes:null' in CNI cache file and it causes nil pointer access at addDefaultGWCacheBytes(). This code change prevents deleteDefaultGWResult() to generate 'routes:null' in cache file.

Fix CNI cache update function to prevent nil access

---

pkg/k8sclient/k8sclient.go
pkg/k8sclient/k8sclient_test.go

interface name should not be limited to DNS-1123 label format. instead validate interface name if provided in pod network annotation in a similar manner as iproute2[1].
this will allow to request interface names such as: "uplink_p0"
[1]https://github.com/iproute2/iproute2/blob/11740815bfe69d6ee2cad7c608a8edc70147209a/lib/utils.c#L832

Change Validation of interface name

---

.github/workflows/kind-e2e.yml
.gitignore
docs/how-to-use.md
e2e/get_tools.sh
e2e/setup_cluster.sh
e2e/templates/dra-integration.yml.j2
e2e/templates/multus-daemonset-thick.yml.j2
e2e/test-dra-integration.sh
pkg/kubeletclient/kubeletclient.go
pkg/kubeletclient/kubeletclient_test.go

Dynamic Resource Allocation was added to k8s 1.26 [1]. 
In k8s 1.27 we added PodResources API to expose the dynamic resources from kubelet.
This PR allow multus to get Dynamic Resource from the podResource API and pass it to CNI as DeviceID.
To use this you will need k8s .127 with DynamicResourceAllocation and  KubeletPodResourcesDynamicResources feature gates enabled. 
[1] - https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3063-dynamic-resource-allocation
[2] - https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3695-pod-resources-for-dra

add support for Dynamic Resource Allocation

---

pkg/server/api/shim.go

https://github.com/k8snetworkplumbingwg/multus-cni/actions/runs/9225475657 recommends to change the code, so this PR fix the code. In addition, APIReadyCheckFunc  can be decaptalize (i.e not expose this type to outisde of package), so change it decaptalized.
```
comment on exported type APIReadyCheckFunc should be of the form "APIReadyCheckFunc ..." (with optional leading article) test (1.21.x, ubuntu-latest): pkg/server/api/shim.go#L44
type name will be used as api.APIReadyCheckFunc by other packages, and that stutters; consider calling this ReadyCheckFunc
```

Not exposed APIReadyCheckFunc to outside of package

---

deployments/multus-daemonset-thick.yml

This is needed to avoid issues with volume unmounts when (other) pods exit as by default kubernetes mounts as private.

Add mountPropagation to host-var-lib-kubelet

---

docs/how-to-use.md
e2e/test-dra-integration.sh

With Kubernetes 1.31, the DRA API will change ([1],[2]). The dra example implementation has already been updated to some extent to reflect those changes. Current e2e tests fail because of that.
With this PR, we add additional info in the docs to reflect the versions of Kubernetes that multus supports DRA and also we fix the e2e test by pinning it to the original DRA example implementation.
Next step is to adjust the multus DRA integration to the new DRA API.
**Note:** The currently opened PRs will need to be rebased on top of master once this PR is merged to ensure that e2e test is passing.
[1]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4381-dra-structured-parameters
[2]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3063-dynamic-resource-a …

Update DRA integration info and fix e2e test

---

cmd/thin_entrypoint/main.go
docs/how-to-use.md
pkg/signals/signals.go

- if cleanup-config-on-exit is set delete generated multus
config file on exit.
- add an option to skip watch for master cni config and kubeconfig
as cleanup-config-on-exit with multus-conf-file=auto also triggered
the watch for cases when deletion of multus config is desired but watch isnt
- setup signal handling to allow config file cleanup on exit

Cleanup multus conf on exit

---

cmd/thin_entrypoint/main.go
cmd/thin_entrypoint/main_test.go

This is a small rework of PR#1302 to reduce code changes for test.
Fixes #1295

create multus kubeconfig for in case of non auto flag.

---

go.mod
go.sum
pkg/k8sclient/k8sclient_test.go
pkg/multus/multus.go
pkg/types/conf_test.go
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
vendor/modules.txt

NOTE: This functionality is dependent on https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/pull/68 and will require a library update in this PR in order to be complete.
This functionality properly represents Network Status for CNI ADD results that return multiple interfaces themselves.
This approach uses a new method from the net-attach-def-client -- `CreateNetworkStatuses`, and refactors to account for the array return.
With the previous method, it's somewhat buggy. If multiple pod interfaces are present, it returns the last one -- and groups all of the IP addresses to that address.
For replication of the error yourself, and to see the fix in action, see this gist: https://gist.github.com/dougbtv/1eb8ac2d61d494b56d65a6b236a86e61
For the related suggested update …

Updates to use CreateNetworkStauses from net-attach-def client, bump to v1.7.1

---

README.md
docs/how-to-use.md

Fixes https://github.com/k8snetworkplumbingwg/multus-cni/issues/1315
Updates the install doc from cloning and install to using url to install.
/cc @dougbtv

Doc: change install from file to url in readme, how-to-use

---

go.mod
go.sum
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
vendor/modules.txt

This fixes the default:true for multiple interface returns from CNI for cluster default network, where all interfaces in that return were marked as default:true in the network-status

Bumps net-attach-def client library to v1.7.2

---

go.mod
go.sum
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
vendor/modules.txt

Previous version didn't account for accounts for the sandox interfaces when reporting the interfaces in the network-status annotation when calculating the default:true interface

Bumps net-attach-def client to v1.7.3

---

go.mod
go.sum
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
vendor/modules.txt

Which improves backwards compatibility for network-status in latest updates to the client library, especially related to Calico.
See also: https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/pull/72

Updates net-attach-def client library to v1.7.4

---

go.mod
go.sum
vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
vendor/modules.txt

From the release notes:
> This release contains a fix related to the determination of the default interface, e.g. setting the default parameter to true in the network-status annotation based on the presence of a gateway in the CNI ADD success result ips.gateway and makes the determination of the default based on the first interface that has an associated value of gateway (using the interface index in the ips element in the CNI ADD success result).
> This provides flexibility especially in CRI-O which uses the first interface and IP addresses for the pod.IP in Kubernetes, therefore. Containerd functionality is unchanged in that it uses the value for the IP addresses specifically
> It's worth noting that CNI ADD success results which do not contain any interfaces will be discarded in this …

Update net-attach-def client library to 1.7.5 for cri-o functionality

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/test.yml
images/Dockerfile
images/Dockerfile.debug
images/Dockerfile.thick

This PR will address a CVE, reported in #1354

Support go 1.22 and 1.23 build to fix CVE

---

pkg/k8sclient/k8sclient.go
pkg/multus/multus.go

If Multus plugin gets a DEL request, but the API Server is down (e.g. via 'crictl rmp'), the call takes so long, it actually never finishes. This prevents CRI-O from deleting the Pods.
Proposed fix sets a timeout for Pods().Get() using context.

Thin plugin: don't wait too long for an answer from API Server

---

pkg/k8sclient/k8sclient.go
pkg/multus/multus.go

From [openshift pull request](https://github.com/openshift/multus-cni/pull/246):
> This makes sure that stale caches never result in NotFound errors.
It was explained to me that informers are almost always are more efficient, and in most cases will work, but a live lookup is appropriate after a number of failures.
This happens only on the retry portion, so we're still getting the benefits of informers, but, on a retry situation, we don't get a cache miss.

always attempt a live pod get on miss to confirm its really not there

---

.github/workflows/kind-e2e.yml
docs/development.md
e2e/README.md
e2e/get_tools.sh
e2e/sed_generate_yaml.sh
e2e/setup_cluster.sh
images/Dockerfile.thick

Otherwise, the latest changes to DRA (which is beta in K8s 1.32) are incompatible.
Additionally, this fixes lint in the Dockerfile.
And adds a couple notes in the docs.
And lastly, bumps kind to `v0.27.0`
Fixes #1403

The e2e kind config should use api/beta for the runtimeConfig

---

pkg/multus/multus.go

sometimes pods get deleted super fast (like jobs or CI) and they come back as not found.
instead of erroring, just return an empty CNI result so things don't blow up.
adds a sentinel `errPodNotFound` and skips the rest of CmdAdd when we hit it.
shouts to race conditions.

handle pod not found during CNI ADD gracefully

---

images/Dockerfile
images/Dockerfile.debug

Pretty simple change. Would allow Kubernetes deployments to specify just args instead of both command + args.

fix: dockerfile change cmd to entrypoint
